---
output: word_document
---
The elevation gradient of saxicolous lichen species richness in the Comeragh Mountains, Co. Waterford, IRE.

author: "Sean Walsh"
date: "05 August 2016
---

```{r eval=FALSE}
setwd("~/MyDataSources")

library(ggplot2)
library(psych)
library(gridExtra)
library(vegan)
library(plyr)
library(reshape2)
library(Hmisc)
library(mgcv)

lichen_df1 <- read.csv("Comeragh_lichen_data1.csv")

cor(lichen_df1[,2:9])
mean(lichen_df1$TOTAL.NO..SPECIES)
var(lichen_df1$TOTAL.NO..SPECIES)
```


```{r eval=FALSE}
ggplot(lichen_df1,aes(x=ELEVATION..m.,y=TOTAL.NO..SPECIES)) +
  geom_point(alpha=1/2) +
  scale_x_continuous(breaks=seq(200,800,100)) +
  xlab("Elevation (m)") +
  ylab("Species richness") +
  theme_bw(base_size = 12)

ggplot(lichen_df1,aes(x=ELEVATION..m.,y=TOTAL.NO..SPECIES)) +
  geom_point(alpha=1/2) +
  stat_smooth(method = "gam",formula = y ~ s(x,k=4),fill=NA) +
  stat_smooth(method = "lm",formula = y ~ x,size=1,fill=NA,colour="black") +
  stat_smooth(method="loess",colour="red",fill=NA) +
  stat_smooth(method = "lm",formula = y ~ poly(x,3),fill=NA,colour="green",span = 0.6) +
  scale_x_continuous(breaks=seq(200,800,100)) +
  scale_y_continuous(breaks = seq(10,20,1),limits = c(10,20)) +
  xlab("Elevation (m)") +
  ylab("Species richness") +
  theme_bw(base_size = 12)      

gam.1 <- gam(TOTAL.NO..SPECIES ~ s(ELEVATION..m.,k=4) + s(WIND.SPEED,k=4) + s(ANNUAL.MEAN.TEMPERATURE,k=4) + s(AVG..MONTHLY.RAINFALL,k=4),data=lichen_df1,select = TRUE) 

gam.2 <- gam(TOTAL.NO..SPECIES ~ s(WIND.SPEED,k=4) + s(ANNUAL.MEAN.TEMPERATURE,k=4) + s(AVG..MONTHLY.RAINFALL,k=4),data=lichen_df1,select = TRUE)  

gam.3 <- gam(TOTAL.NO..SPECIES ~ s(WIND.SPEED,k=4) + s(AVG..MONTHLY.RAINFALL,k=4),data=lichen_df1,select = TRUE) 


anova(gam.1,gam.2,gam.3,test="F")
par(mfrow=c(1,2))
plot(gam.3)

ggplot(lichen_df1,aes(x=WIND.SPEED,y=TOTAL.NO..SPECIES)) +
  geom_point(alpha=1/2) +
  xlab("Wind speed (m/s)") +
  ylab("Species richness") +
  scale_x_continuous(breaks = seq(4,13,1),limits = c(5,13)) +
  scale_y_continuous(breaks = seq(10,20,1),limits = c(10,20)) +
  theme_bw(base_size = 12) +
  stat_smooth(method="gam",formula=y~s(x,k=4),fill=NA,colour="black") +
  annotate("text", label = "R2 = 0.45", x = 7, y = 19) 

  
wind.gam <- gam(TOTAL.NO..SPECIES ~ s(WIND.SPEED,k=4),data=lichen_df1)
summary(wind.gam)


```


```{r eval=FALSE}

cru.gam <- gam(NO..CRUSTOSE ~ s(ELEVATION..m.,k=4),data=lichen_df1)
fol.gam <- gam(NO..FOLIOSE ~ s(ELEVATION..m.,k=4),data=lichen_df1)
fru.gam <- gam(NO..FRUTICOSE ~ s(ELEVATION..m.,k=4),data=lichen_df1)
tot.gam <- gam(TOTAL.NO..SPECIES ~ s(ELEVATION..m.,k=4),data=lichen_df1)


p1 <- ggplot(lichen_df1,aes(x=ELEVATION..m.,y=TOTAL.NO..SPECIES)) +
        geom_point(alpha=1/2) +
        scale_x_continuous(breaks=seq(200,800,100)) +
        scale_y_continuous(breaks = seq(10,20,1),limits = c(10,20)) +
        xlab("Elevation (m)") +
        ylab("Species richness") +
        theme_bw(base_size = 12) +
        annotate("text", label = "R2 = 0.35", x = 300, y = 19) +
        stat_smooth(method = "gam",formula = y ~ s(x,k=4),fill=NA,colour="black")

p2 <- ggplot(lichen_df1,aes(x=ELEVATION..m.,y=NO..CRUSTOSE)) +
      geom_point(alpha=1/2) + 
      stat_smooth(method="gam",formula=y ~ s(x,k=4),fill=NA,colour="black") +
      scale_x_continuous(breaks = seq(200,800,100)) +
      xlab("Elevation (m)") +
      ylab("Crustose richness") +
      theme_bw(base_size = 12) +
      annotate("text", label = "R2 = 0.55", x = 300, y = 11)
                        
p3 <- ggplot(lichen_df1,aes(x=ELEVATION..m.,y=NO..FOLIOSE)) +
      geom_point(alpha=1/2) +
      stat_smooth(method="gam",formula=y ~ s(x,k=4),fill=NA,colour="black") +
      scale_x_continuous(breaks = seq(200,800,100)) +
      xlab("Elevation (m)") +
      ylab("Foliose richness") +
      theme_bw(base_size = 12) +
      annotate("text", label = "R2 = 0.66", x = 250, y = 4.5)

p4 <- ggplot(lichen_df1,aes(x=ELEVATION..m.,y=NO..FRUTICOSE)) +
      geom_point(alpha=1/2) +
      stat_smooth(method="gam",formula=y ~ s(x,k=4),fill=NA,colour="black") +
      scale_x_continuous(breaks = seq(200,800,100)) +
      xlab("Elevation (m)") +
      ylab("Fruticose richness") +
      theme_bw(base_size = 12) +
      annotate("text", label = "R2 = 0.60", x = 400, y = 5)

grid.arrange(p1,p2,p3,p4,ncol=2)

```


```{r eval=FALSE}
ggplot(lichen_df1,aes(x=ELEVATION..m.,y=WIND.SPEED)) +
  geom_point(alpha=1/2) +
  stat_smooth(method="lm",formula = y ~ x,size=1,colour="black",fill=NA) +
  scale_x_continuous(breaks = seq(200,800,100)) +
  xlab("Elevation (m)") +
  ylab("Wind speed (m/s)") +
  annotate("text", label = "R2 = 0.78", x = 300, y = 12) +
  theme_bw(base_size = 12)

wind.lm <- lm(WIND.SPEED ~ ELEVATION..m.,data = lichen_df1)
summary(wind.lm)
```


```{r eval=FALSE}

species <- read.csv("rank_abundance_data.csv")
species["Sum",] <- colSums(species)
species["Species",] <- colnames(species)

species.rank <- t(species)
write.table(species.rank, "speRank.txt", sep="\t", row.names = FALSE)

speRank <- read.delim("speRank.txt", header = TRUE)
View(speRank)

speRank$Species <- factor(speRank$Species, levels = speRank$Species)

bar <- ggplot(speRank,aes(x=reorder(Species,-Sum), y=Sum))
              
bar + stat_summary(geom = "bar",colour="black",fill="black") + labs(x = "", y = "Abundance") + theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  scale_y_continuous(breaks = seq(0,300,50)) 

```


