#Command List
```{r}
getwd()
list.files()
read.csv("tminvcanopyind.csv")
data.tmin = read.csv("tminvcanopyind.csv")
dim(data.tmin)
str(data.tmin)
names(data.tmin)
head(data.tmin)
plot(data.tmin)
eruption.lm = lm(eruptions ~ waiting, data=faithful)
wages.lm = lm(earned ~ hours, data=data.income)
minT.lm = lm(Tmin~`canopy index`, data=data.tmin)
summary(wages.lm)
vec2 = scan()
vec1 = scan()
```





> summary(Tmin.lm)
help(summary.lm)

plot(data.range, col = c("gray99"))
colours()
abline(Drange.lm)
abline(Drange.lm, col="blue")
abline(Drange.lm, col="black")
abline(coef(my_lm))

install.packages('ggplot2')
library(ggplot2)
#scatter plot of diamond price versus carat colour


names(data.income) <- c("work hours", "earnings / $")

#scatter plot of Tmin against canopy index:
qplot(x=`canopy index`, y=Tmin)


qplot(data = data.lf, x = Latitude, y = Canopy.index, colour = Species) + scale_colour_brewer(palette = 'Accent')

#When receiving this error message:
Error in .Call.graphics(C_palette2, .Call(C_palette2, NULL)) : 
  invalid graphics state
#simply enter this line of code: 
dev.off()
#and run the plot again

qplot(data = data.surface, x = Canopy.Index, y = X.Tmin, colour = Surface.Cover) + scale_colour_brewer(palette = 'Accent')
> plot.T <- qplot(data = data.surface, x = Canopy.Index, y = X.Tmin, colour = Surface.Cover) + scale_colour_brewer(palette = 'Accent')
> model.T <- leaffall.lm
> coef(model.T)
 (Intercept) Canopy.Index 
  -0.6755105   -0.0176685 
> plot.T + geom_abline(intercept=coef(model.T)[1], slope=coef(model.T)[2]) + scale_x_continuous(breaks=c(5,15,25,35,45,55,65,75,85,95))


#To add a simple regression line using ggplot2:

plot.x <- qplot(y=earned, x=hours, data=data.income)
model.x <- lm(earned ~ hours, data.income)
coef(model.x)
plot.x + geom_abline(intercept=coef(model.x)[1], slope=coef(model.x)[2])

plot.T <- qplot(y=Tmin, x=`canopy index`, data=data.tmin)
model.T <- lm(Tmin ~ `canopy index`, data.tmin)
coef(model.T)
plot.T + geom_abline(intercept=coef(model.T)[1], slope=coef(model.T)[2])
 
#To change x-axis increments:
plot.T + geom_abline(intercept=coef(model.T)[1], slope=coef(model.T)[2]) + scale_x_continuous(breaks=c(5,15,25,35,45,55,65,75,85,95))

 
#density plots:
#build data frames

vec1 <- data.frame(x=vec1)
> vec2 <- data.frame(x=vec2)
> ggplot() + geom_density(aes(x=x), colour="red", data=vec1) + geom_density(aes(x=x), colour="green", data=vec2) + xlim(-20, 100

#to add colours and fill:

stacked_sean <- stack(data.stand)

ggplot(stacked_sean, aes(x=values)) + geom_density(aes(group=ind, colour=ind, fill=ind), alpha=0.3) + xlim(-20, 100) + xlab("")

ggplot(stacked_sean, aes(x=values)) + geom_density(aes(group=ind, colour=ind, fill=ind), alpha=0.3) + xlim(-20, 100) + xlab("canopy index")

#standard R boxplots:
#create a dataframe of variables in columns and observations in rows

boxplot(stand, col = "yellow1","red")
boxplot(stand, col = "red", ylab = "canopy index", xlab = "stand")

#boxplots using ggplot2:
ggplot(stand, aes(x=Stand, y=Canopy.index)) + geom_boxplot(notch=TRUE)
p <- ggplot(stand, aes(x=Stand, y=Canopy.index)) + geom_boxplot(notch=TRUE)
#name the plot

#to change increments on axes:
p + scale_y_continuous(breaks=c(5,15,25,35,45,55,65,75,85,95))
#to use colourbrewer package to change box colours:
p+scale_fill_brewer(palette="Dark2")
p + scale_y_continuous(breaks=c(5,15,25,35,45,55,65,75,85,95))

# movies is pre-loaded in your workspace

# Build the grid matrix
grid <- matrix(c(1, 2, 3, 3), nrow = 2)

# Specify the layout
layout(grid)

# Customize the three plots
plot(movies$rating, movies$runtime, xlab = "Rating", ylab = "Runtime", pch = 4)
plot(movies$votes, movies$runtime, xlab = "Number of Votes", ylab = "Runtime", col = "blue")
boxplot(movies$runtime, border = "darkgray", main = "Boxplot of Runtime")



